In [72]:
import pandas as pd
from ucimlrepo import fetch_ucirepo
  
# fetch dataset 
tic_tac_toe_endgame = fetch_ucirepo(id=101) 
  
# data (as pandas dataframes) 
X = tic_tac_toe_endgame.data.features 
y = tic_tac_toe_endgame.data.targets 

X

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square
0,x,x,x,x,o,o,x,o,o
1,x,x,x,x,o,o,o,x,o
2,x,x,x,x,o,o,o,o,x
3,x,x,x,x,o,o,o,b,b
4,x,x,x,x,o,o,b,o,b
...,...,...,...,...,...,...,...,...,...
953,o,x,x,x,o,o,o,x,x
954,o,x,o,x,x,o,x,o,x
955,o,x,o,x,o,x,x,o,x
956,o,x,o,o,x,x,x,o,x
957,o,o,x,x,x,o,o,x,x

In [73]:
# transform categorical variables to numerical using label encoding
from sklearn.preprocessing import LabelEncoder
X_label = pd.DataFrame()
le = LabelEncoder()
for column in X.columns:
    X_label[column] = le.fit_transform(X[column]) # x:2, o:1, b:0

# transform target variable to numerical
y_label = y['class'].map({'positive': 1, 'negative': 0})
pd.concat([X_label, y_label], axis=1)

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,class
0,2,2,2,2,1,1,2,1,1,1
1,2,2,2,2,1,1,1,2,1,1
2,2,2,2,2,1,1,1,1,2,1
3,2,2,2,2,1,1,1,0,0,1
4,2,2,2,2,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
953,1,2,2,2,1,1,1,2,2,0
954,1,2,1,2,2,1,2,1,2,0
955,1,2,1,2,1,2,2,1,2,0
956,1,2,1,1,2,2,2,1,2,0
957,1,1,2,2,2,1,1,2,2,0

In [75]:
# implement descision tree classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_label, y_label, test_size=0.2, random_state=42)
# create decision tree classifier
clf = DecisionTreeClassifier(random_state=42)
# train the classifier
clf.fit(X_train, y_train)
# make predictions
y_pred = clf.predict(X_test)
# evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Error Rate: {(1 - accuracy) * 100:.2f}%')

Accuracy: 87.50%
Error Rate: 12.50%