In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv("datasets/wine.data", header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [27]:
df.std()

0       0.775035
1       0.811827
2       1.117146
3       0.274344
4       3.339564
5      14.282484
6       0.625851
7       0.998859
8       0.124453
9       0.572359
10      2.318286
11      0.228572
12      0.709990
13    314.907474
dtype: float64

In [28]:
df = df/df.std()
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.290264,17.528375,1.530686,8.857492,4.671269,8.892011,4.473908,3.063496,2.249839,4.000986,2.432832,4.549997,5.521201,3.381946
1,1.290264,16.259631,1.593346,7.800425,3.353731,7.001583,4.234234,2.763154,2.089136,2.236359,1.889327,4.593747,4.788797,3.334313
2,1.290264,16.210359,2.112526,9.732307,5.569590,7.071599,4.473908,3.243702,2.410542,4.909507,2.450086,4.506247,4.464849,3.763010
3,1.290264,17.700826,1.745519,9.112647,5.030597,7.911789,6.151623,3.493988,1.928434,3.808799,3.364555,3.762498,4.859220,4.699793
4,1.290264,16.308903,2.318408,10.461318,6.288246,8.261868,4.473908,2.693074,3.133705,3.179823,1.863446,4.549997,4.126816,2.334019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3.870793,16.887844,5.057530,8.930394,6.138526,6.651504,2.684345,0.610697,4.178273,1.851985,3.321420,2.799998,2.450737,2.349897
174,3.870793,16.505989,3.499990,9.039745,6.887127,7.141615,2.876084,0.750857,3.455110,2.463489,3.148878,3.062498,2.197213,2.381652
175,3.870793,16.345856,3.831191,8.237833,5.988806,8.401900,2.540541,0.690788,3.455110,2.358660,4.399803,2.581248,2.197213,2.651573
176,3.870793,16.222677,2.318408,8.638789,5.988806,8.401900,2.636410,0.680777,4.258624,2.550847,4.011585,2.624998,2.281721,2.667450
177,3.870793,17.405196,3.670066,9.987461,7.336288,6.721520,3.275540,0.760868,4.499678,2.358660,3.968449,2.668748,2.253552,1.778300

In [29]:
df.mean()

0      2.500793
1     16.014034
2      2.091354
3      8.626093
4      5.837572
5      6.983489
6      3.667186
7      2.031588
8      2.907547
9      2.779548
10     2.181823
11     4.188839
12     3.678480
13     2.371786
dtype: float64

In [30]:
df.std()

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
dtype: float64

In [31]:
df.to_csv("inc-b_wine.csv")